# Generated by Django 4.0.2 on 2022-09-16 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_matauang_kode_matauang'),
    ]

    operations = [
        migrations.AddField(
            model_name='matauang',
            name='negara',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
