# Generated by Django 4.0.2 on 2022-09-29 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_kurs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_prod', models.IntegerField(null=True)),
                ('nama_produk', models.CharField(max_length=100, null=True)),
                ('tgl_aktif', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('', 'NonAktif'), ('1', 'Aktif')], max_length=4)),
            ],
            options={
                'verbose_name': 'Produk',
                'verbose_name_plural': 'Produk',
                'db_table': 'produk',
            },
        ),
        migrations.AlterField(
            model_name='kurs',
            name='status_kurs',
            field=models.CharField(choices=[('', 'NonAktif'), ('1', 'Aktif')], max_length=10),
        ),
        migrations.AlterField(
            model_name='matauang',
            name='status',
            field=models.CharField(choices=[('', 'NonAktif'), ('1', 'Aktif')], max_length=10, null=True),
        ),
    ]
