# Generated by Django 4.0.2 on 2022-09-29 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_produk_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produk',
            name='status',
            field=models.CharField(blank=True, choices=[('', 'NonAktif'), ('1', 'Aktif')], max_length=20, null=True),
        ),
    ]
