# Generated by Django 4.0.2 on 2022-09-29 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_produk_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kurs',
            name='status_kurs',
            field=models.CharField(choices=[('0', 'NonAktif'), ('1', 'Aktif')], default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='matauang',
            name='status',
            field=models.CharField(choices=[('0', 'NonAktif'), ('1', 'Aktif')], default=0, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='produk',
            name='status',
            field=models.CharField(blank=True, choices=[('0', 'NonAktif'), ('1', 'Aktif')], default=0, max_length=20, null=True),
        ),
    ]
