# Generated by Django 4.0.2 on 2022-09-29 21:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0009_produk_cu'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParameterData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_param', models.CharField(blank=True, choices=[('0', 'NonAktif'), ('1', 'Aktif')], default=0, max_length=20, null=True)),
                ('tgl_aktif_param', models.DateField(blank=True, null=True)),
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('cu', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cu_paramdata', to=settings.AUTH_USER_MODEL)),
                ('nilai_kurs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.kurs')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.produk')),
            ],
            options={
                'verbose_name': 'ParameterData',
                'db_table': 'parameterdata',
            },
        ),
        migrations.CreateModel(
            name='JasaPengiriman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_jasa_pengiriman', models.CharField(max_length=100, null=True)),
                ('alamat', models.CharField(max_length=100, null=True)),
                ('telepon', models.CharField(max_length=20, null=True)),
                ('status', models.CharField(blank=True, choices=[('0', 'NonAktif'), ('1', 'Aktif')], default=0, max_length=20, null=True)),
                ('cu', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cu_js', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'JasaPengiriman',
                'db_table': 'jasapengiriman',
            },
        ),
    ]
