# Generated by Django 4.0.2 on 2022-09-29 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_parameterdata_jasa_pengiriman'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameterdata',
            name='airfreight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parameterdata',
            name='fuel_surcharge',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parameterdata',
            name='gst_zero_rated',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parameterdata',
            name='handling_charges',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parameterdata',
            name='import_handling_charges',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parameterdata',
            name='insurance_security_surcharge',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
