# Generated by Django 4.0.2 on 2022-10-01 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_parameterdata_airfreight_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parameterdata',
            old_name='airfreight',
            new_name='man_overweight_charges_surcharge',
        ),
        migrations.RenameField(
            model_name='parameterdata',
            old_name='fuel_surcharge',
            new_name='max_airfreight',
        ),
        migrations.RenameField(
            model_name='parameterdata',
            old_name='gst_zero_rated',
            new_name='max_airfreight_charges',
        ),
        migrations.RenameField(
            model_name='parameterdata',
            old_name='handling_charges',
            new_name='max_airfreight_import_handling',
        ),
        migrations.RenameField(
            model_name='parameterdata',
            old_name='import_handling_charges',
            new_name='max_akses_bandara_inspeksi',
        ),
        migrations.RenameField(
            model_name='parameterdata',
            old_name='insurance_security_surcharge',
            new_name='max_awb_fee',
        ),
        migrations.AddField(
            model_name='parameterdata',
            name='admin_fee',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='parameterdata',
            name='airfreight_sin_dps_dil',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='parameterdata',
            name='fee_collection',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='parameterdata',
            name='max_cartage_and_warehouse_charge',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parameterdata',
            name='max_delivery',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parameterdata',
            name='max_delivey_to_hera',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parameterdata',
            name='max_doc_and_clearance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parameterdata',
            name='max_duty_tax',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parameterdata',
            name='max_export_handling',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parameterdata',
            name='max_forklift_for_heavy_cargo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parameterdata',
            name='max_fuel_surcharge',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parameterdata',
            name='max_ground_handling',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parameterdata',
            name='max_gst_zero_rated',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parameterdata',
            name='max_handling_charge',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parameterdata',
            name='max_handling_charges',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parameterdata',
            name='max_handling_fee',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parameterdata',
            name='max_import_handling_charges',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parameterdata',
            name='max_insurance_security_surcharge',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parameterdata',
            name='max_pjkp2u_dps_dil_at_cost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parameterdata',
            name='max_pjkp2u_sin_dps_at_cost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parameterdata',
            name='max_storage_mcl_e_0389249_at_cost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parameterdata',
            name='max_tax_handling_charge',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parameterdata',
            name='max_warehouse_charge',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parameterdata',
            name='min_airfreight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parameterdata',
            name='min_airfreight_charges',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parameterdata',
            name='min_airfreight_import_handling',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parameterdata',
            name='min_akses_bandara_inspeksi',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parameterdata',
            name='min_awb_fee',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parameterdata',
            name='min_cartage_and_warehouse_charge',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parameterdata',
            name='min_custom_clearance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parameterdata',
            name='min_delivery',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parameterdata',
            name='min_delivey_to_hera',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parameterdata',
            name='min_doc_and_clearance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parameterdata',
            name='min_duty_tax',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parameterdata',
            name='min_export_handling',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parameterdata',
            name='min_forklift_for_heavy_cargo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parameterdata',
            name='min_fuel_surcharge',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parameterdata',
            name='min_ground_handling',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parameterdata',
            name='min_gst_zero_rated',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parameterdata',
            name='min_handling_charge',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parameterdata',
            name='min_handling_charges',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parameterdata',
            name='min_handling_fee',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parameterdata',
            name='min_insurance_security_surcharge',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parameterdata',
            name='min_overweight_charges_surcharge',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parameterdata',
            name='min_pjkp2u_dps_dil_at_cost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parameterdata',
            name='min_pjkp2u_sin_dps_at_cost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parameterdata',
            name='min_storage_at_cost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parameterdata',
            name='min_storage_mcl_e_0389249_at_cost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parameterdata',
            name='min_tax_handling_charge',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parameterdata',
            name='min_warehouse_charge',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parameterdata',
            name='price_airfreight',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='parameterdata',
            name='price_airfreight_charges',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='parameterdata',
            name='price_airfreight_import_handling',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='parameterdata',
            name='price_akses_bandara_inspeksi',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='parameterdata',
            name='price_awb_fee',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='parameterdata',
            name='price_cartage_and_warehouse_charge',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='parameterdata',
            name='price_custom_clearance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='parameterdata',
            name='price_delivery',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='parameterdata',
            name='price_delivey_to_hera',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='parameterdata',
            name='price_doc_and_clearance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='parameterdata',
            name='price_duty_tax',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='parameterdata',
            name='price_export_handling',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='parameterdata',
            name='price_forklift_for_heavy_cargo',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='parameterdata',
            name='price_fuel_surcharge',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='parameterdata',
            name='price_ground_handling',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='parameterdata',
            name='price_gst_zero_rated',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='parameterdata',
            name='price_handling_charge',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='parameterdata',
            name='price_handling_charges',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='parameterdata',
            name='price_handling_fee',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='parameterdata',
            name='price_import_handling_charges',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='parameterdata',
            name='price_insurance_security_surcharge',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='parameterdata',
            name='price_overweight_charges_surcharge',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='parameterdata',
            name='price_pjkp2u_dps_dil_at_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='parameterdata',
            name='price_pjkp2u_sin_dps_at_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='parameterdata',
            name='price_storage_at_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='parameterdata',
            name='price_storage_mcl_e_0389249_at_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='parameterdata',
            name='price_tax_handling_charge',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='parameterdata',
            name='price_warehouse_charge',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
    ]
