# Generated by Django 4.0.2 on 2022-10-01 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_rename_airfreight_parameterdata_man_overweight_charges_surcharge_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameterdata',
            name='jasa_pengiriman',
        ),
        migrations.AddField(
            model_name='produk',
            name='jasa_pengiriman',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.jasapengiriman'),
        ),
    ]
