# Generated by Django 4.0.2 on 2022-10-01 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_remove_parameterdata_jasa_pengiriman_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Negara',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_negara', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(blank=True, choices=[('0', 'NonAktif'), ('1', 'Aktif')], default=0, max_length=20, null=True)),
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('mdate', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'negara',
            },
        ),
    ]
