# Generated by Django 4.0.2 on 2022-10-01 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_negara'),
    ]

    operations = [
        migrations.AddField(
            model_name='produk',
            name='poin_dua',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poin_dua', to='products.jasapengiriman'),
        ),
        migrations.AddField(
            model_name='produk',
            name='poin_satu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poin_satu', to='products.jasapengiriman'),
        ),
        migrations.AddField(
            model_name='produk',
            name='poin_tiga',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poin_tiga', to='products.jasapengiriman'),
        ),
    ]
