# Generated by Django 4.0.2 on 2022-10-01 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_produk_poin_dua_produk_poin_satu_produk_poin_tiga'),
    ]

    operations = [
        migrations.AddField(
            model_name='negara',
            name='singkatan',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
