# Generated by Django 4.0.2 on 2022-10-01 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_remove_produk_poin_dua_remove_produk_poin_satu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produk',
            name='point_dua',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='point_dua', to='products.negara'),
        ),
        migrations.AlterField(
            model_name='produk',
            name='point_satu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='point_satu', to='products.negara'),
        ),
        migrations.AlterField(
            model_name='produk',
            name='point_tiga',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='point_tiga', to='products.negara'),
        ),
    ]
