# Generated by Django 4.0.2 on 2022-10-02 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_alter_produk_point_dua_alter_produk_point_satu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameterdata',
            name='min_import_handling_charges',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
