# Generated by Django 4.0.2 on 2022-10-08 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_parameterdata_min_import_handling_charges'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produk',
            name='jasa_pengiriman',
        ),
        migrations.AddField(
            model_name='produk',
            name='destinations_vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destinetions_v2', to='products.jasapengiriman'),
        ),
        migrations.AddField(
            model_name='produk',
            name='locations_vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations_v3', to='products.jasapengiriman'),
        ),
        migrations.AddField(
            model_name='produk',
            name='origin_vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='origin_v1', to='products.jasapengiriman'),
        ),
    ]
