# Generated by Django 4.0.2 on 2022-10-09 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_parameterdata_high_airfreight_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parameterdata',
            old_name='price_airfreight',
            new_name='price_high_airfreight',
        ),
        migrations.AddField(
            model_name='parameterdata',
            name='price_max_airfreight',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='parameterdata',
            name='price_min_airfreight',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
    ]
