# Generated by Django 4.0.2 on 2022-10-09 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_rename_price_airfreight_parameterdata_price_high_airfreight_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameterdata',
            name='high_airfreight',
        ),
        migrations.RemoveField(
            model_name='parameterdata',
            name='high_handling_charge',
        ),
        migrations.AddField(
            model_name='parameterdata',
            name='price_high_handling_charges',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='parameterdata',
            name='price_max_handling_charges',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='parameterdata',
            name='price_min_handling_charges',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
    ]
