# Generated by Django 4.0.2 on 2022-10-09 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_remove_parameterdata_high_airfreight_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameterdata',
            name='price_high_handling_charges',
        ),
    ]
