# Generated by Django 4.0.2 on 2022-10-09 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_remove_parameterdata_price_high_handling_charges'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parameterdata',
            old_name='max_handling_charges',
            new_name='max_handling_charges_sl',
        ),
        migrations.AddField(
            model_name='parameterdata',
            name='min_handling_charges_sl',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
