# Generated by Django 4.0.2 on 2022-10-09 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_rename_price_handling_charges_parameterdata_price_handling_charges_sl'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameterdata',
            name='price_high_fuel_surcharge',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='parameterdata',
            name='price_high_gst_zero_rated',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='parameterdata',
            name='price_high_import_handling_charges',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='parameterdata',
            name='price_high_insurance_security_surcharge',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
    ]
