# Generated by Django 4.0.2 on 2022-10-09 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_parameterdata_price_high_fuel_surcharge_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameterdata',
            name='max_fuel_surcharge',
        ),
        migrations.RemoveField(
            model_name='parameterdata',
            name='max_gst_zero_rated',
        ),
        migrations.RemoveField(
            model_name='parameterdata',
            name='max_import_handling_charges',
        ),
        migrations.RemoveField(
            model_name='parameterdata',
            name='max_insurance_security_surcharge',
        ),
    ]
