# Generated by Django 4.0.2 on 2022-10-09 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_rename_man_overweight_charges_surcharge_parameterdata_min_fee_collection_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameterdata',
            name='max_airfreight',
            field=models.FloatField(blank=True, help_text='Freigh Solution', null=True),
        ),
        migrations.AlterField(
            model_name='parameterdata',
            name='min_airfreight',
            field=models.FloatField(blank=True, help_text='Freigh Solution', null=True),
        ),
        migrations.AlterField(
            model_name='parameterdata',
            name='price_high_airfreight',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Freigh Solution', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='parameterdata',
            name='price_max_airfreight',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Freigh Solution', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='parameterdata',
            name='price_min_airfreight',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Freigh Solution', max_digits=12, null=True),
        ),
    ]
