# Generated by Django 4.0.2 on 2022-10-09 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0032_alter_parameterdata_max_airfreight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameterdata',
            name='admin_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='LOGISTIK DILI', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='parameterdata',
            name='admin_high_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='LOGISTIK DILI', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='parameterdata',
            name='fee_collection',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='LOGISTIK DILI', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='parameterdata',
            name='fee_high_collection',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='LOGISTIK DILI', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='parameterdata',
            name='min_admin_fee',
            field=models.FloatField(blank=True, help_text='LOGISTIK DILI', null=True),
        ),
        migrations.AlterField(
            model_name='parameterdata',
            name='min_airfreight_charges',
            field=models.FloatField(blank=True, help_text='Sholid Logistik', null=True),
        ),
        migrations.AlterField(
            model_name='parameterdata',
            name='min_akses_bandara_inspeksi',
            field=models.FloatField(blank=True, help_text='LOGISTIK DILI', null=True),
        ),
        migrations.AlterField(
            model_name='parameterdata',
            name='min_awb_fee',
            field=models.FloatField(blank=True, help_text='Sholid Logistik', null=True),
        ),
        migrations.AlterField(
            model_name='parameterdata',
            name='min_custom_clearance',
            field=models.FloatField(blank=True, help_text='LOGISTIK DILI', null=True),
        ),
        migrations.AlterField(
            model_name='parameterdata',
            name='min_delivey_to_hera',
            field=models.FloatField(blank=True, help_text='LOGISTIK DILI', null=True),
        ),
        migrations.AlterField(
            model_name='parameterdata',
            name='min_fee_collection',
            field=models.FloatField(blank=True, help_text='LOGISTIK DILI', null=True),
        ),
        migrations.AlterField(
            model_name='parameterdata',
            name='min_forklift_for_heavy_cargo',
            field=models.FloatField(blank=True, help_text='LOGISTIK DILI', null=True),
        ),
        migrations.AlterField(
            model_name='parameterdata',
            name='min_fuel_surcharge',
            field=models.FloatField(blank=True, help_text='Freigh Solution', null=True),
        ),
        migrations.AlterField(
            model_name='parameterdata',
            name='min_gst_zero_rated',
            field=models.FloatField(blank=True, help_text='Freigh Solution', null=True),
        ),
        migrations.AlterField(
            model_name='parameterdata',
            name='min_handling_charges',
            field=models.FloatField(blank=True, help_text='Freigh Solution', null=True),
        ),
        migrations.AlterField(
            model_name='parameterdata',
            name='min_handling_charges_sl',
            field=models.FloatField(blank=True, help_text='Sholid Logistik', null=True),
        ),
        migrations.AlterField(
            model_name='parameterdata',
            name='min_handling_fee',
            field=models.FloatField(blank=True, help_text='LOGISTIK DILI', null=True),
        ),
        migrations.AlterField(
            model_name='parameterdata',
            name='min_import_handling_charges',
            field=models.FloatField(blank=True, help_text='Freigh Solution', null=True),
        ),
        migrations.AlterField(
            model_name='parameterdata',
            name='min_insurance_security_surcharge',
            field=models.FloatField(blank=True, help_text='Freigh Solution', null=True),
        ),
        migrations.AlterField(
            model_name='parameterdata',
            name='min_overweight_charges_surcharge',
            field=models.FloatField(blank=True, help_text='Sholid Logistik', null=True),
        ),
        migrations.AlterField(
            model_name='parameterdata',
            name='min_pjkp2u_dps_dil_at_cost',
            field=models.FloatField(blank=True, help_text='Sholid Logistik', null=True),
        ),
        migrations.AlterField(
            model_name='parameterdata',
            name='min_pjkp2u_sin_dps_at_cost',
            field=models.FloatField(blank=True, help_text='Sholid Logistik', null=True),
        ),
        migrations.AlterField(
            model_name='parameterdata',
            name='min_storage_at_cost',
            field=models.FloatField(blank=True, help_text='Sholid Logistik', null=True),
        ),
        migrations.AlterField(
            model_name='parameterdata',
            name='min_storage_mcl_e_0389249_at_cost',
            field=models.FloatField(blank=True, help_text='Sholid Logistik', null=True),
        ),
        migrations.AlterField(
            model_name='parameterdata',
            name='price_airfreight_charges',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Sholid Logistik', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='parameterdata',
            name='price_akses_bandara_inspeksi',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='LOGISTIK DILI', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='parameterdata',
            name='price_awb_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Sholid Logistik', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='parameterdata',
            name='price_custom_clearance',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='LOGISTIK DILI', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='parameterdata',
            name='price_delivey_to_hera',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='LOGISTIK DILI', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='parameterdata',
            name='price_forklift_for_heavy_cargo',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='LOGISTIK DILI', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='parameterdata',
            name='price_fuel_surcharge',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Freigh Solution', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='parameterdata',
            name='price_gst_zero_rated',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Freigh Solution', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='parameterdata',
            name='price_handling_charges_sl',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Sholid Logistik', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='parameterdata',
            name='price_handling_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='LOGISTIK DILI', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='parameterdata',
            name='price_high_airfreight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Freigh Solution', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='parameterdata',
            name='price_high_airfreight_charges',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Sholid Logistik', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='parameterdata',
            name='price_high_akses_bandara_inspeksi',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='LOGISTIK DILI', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='parameterdata',
            name='price_high_awb_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Sholid Logistik', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='parameterdata',
            name='price_high_custom_clearance',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='LOGISTIK DILI', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='parameterdata',
            name='price_high_delivey_to_hera',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='LOGISTIK DILI', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='parameterdata',
            name='price_high_forklift_for_heavy_cargo',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='LOGISTIK DILI', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='parameterdata',
            name='price_high_fuel_surcharge',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Freigh Solution', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='parameterdata',
            name='price_high_ground_handling',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='LOGISTIK DILI', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='parameterdata',
            name='price_high_gst_zero_rated',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Freigh Solution', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='parameterdata',
            name='price_high_handling_charges_sl',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Sholid Logistik', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='parameterdata',
            name='price_high_handling_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='LOGISTIK DILI', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='parameterdata',
            name='price_high_import_handling_charges',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Freigh Solution', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='parameterdata',
            name='price_high_insurance_security_surcharge',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Freigh Solution', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='parameterdata',
            name='price_high_overweight_charges_surcharge',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Sholid Logistik', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='parameterdata',
            name='price_high_pjkp2u_dps_dil_at_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Sholid Logistik', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='parameterdata',
            name='price_high_pjkp2u_sin_dps_at_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Sholid Logistik', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='parameterdata',
            name='price_high_storage_at_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Sholid Logistik', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='parameterdata',
            name='price_high_storage_mcl_e_0389249_at_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Sholid Logistik', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='parameterdata',
            name='price_import_handling_charges',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Freigh Solution', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='parameterdata',
            name='price_insurance_security_surcharge',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Freigh Solution', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='parameterdata',
            name='price_max_airfreight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Freigh Solution', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='parameterdata',
            name='price_max_handling_charges',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Freigh Solution', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='parameterdata',
            name='price_min_airfreight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Freigh Solution', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='parameterdata',
            name='price_min_handling_charges',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Freigh Solution', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='parameterdata',
            name='price_overweight_charges_surcharge',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Sholid Logistik', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='parameterdata',
            name='price_pjkp2u_dps_dil_at_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Sholid Logistik', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='parameterdata',
            name='price_pjkp2u_sin_dps_at_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Sholid Logistik', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='parameterdata',
            name='price_storage_at_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Sholid Logistik', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='parameterdata',
            name='price_storage_mcl_e_0389249_at_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Sholid Logistik', max_digits=12, null=True),
        ),
    ]
