# Generated by Django 4.0.2 on 2022-10-10 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0033_alter_parameterdata_admin_fee_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parameterdata',
            old_name='price_high_ground_handling',
            new_name='price_ground_handling_dl',
        ),
        migrations.AddField(
            model_name='parameterdata',
            name='min_ground_handling_dl',
            field=models.FloatField(blank=True, help_text='LOGISTIK DILI', null=True),
        ),
        migrations.AddField(
            model_name='parameterdata',
            name='price_high_ground_handling_dl',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='LOGISTIK DILI', max_digits=12, null=True),
        ),
    ]
