# Generated by Django 4.0.2 on 2022-10-10 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0034_rename_price_high_ground_handling_parameterdata_price_ground_handling_dl_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameterdata',
            name='airfreight_sin_dps_dil',
        ),
        migrations.RemoveField(
            model_name='parameterdata',
            name='max_airfreight_import_handling',
        ),
        migrations.RemoveField(
            model_name='parameterdata',
            name='max_cartage_and_warehouse_charge',
        ),
        migrations.RemoveField(
            model_name='parameterdata',
            name='max_delivery',
        ),
        migrations.RemoveField(
            model_name='parameterdata',
            name='max_doc_and_clearance',
        ),
        migrations.RemoveField(
            model_name='parameterdata',
            name='max_duty_tax',
        ),
        migrations.RemoveField(
            model_name='parameterdata',
            name='max_export_handling',
        ),
        migrations.RemoveField(
            model_name='parameterdata',
            name='max_ground_handling',
        ),
        migrations.RemoveField(
            model_name='parameterdata',
            name='max_handling_charge',
        ),
        migrations.RemoveField(
            model_name='parameterdata',
            name='max_tax_handling_charge',
        ),
        migrations.RemoveField(
            model_name='parameterdata',
            name='max_warehouse_charge',
        ),
        migrations.RemoveField(
            model_name='parameterdata',
            name='min_airfreight_import_handling',
        ),
        migrations.RemoveField(
            model_name='parameterdata',
            name='min_cartage_and_warehouse_charge',
        ),
        migrations.RemoveField(
            model_name='parameterdata',
            name='min_delivery',
        ),
        migrations.RemoveField(
            model_name='parameterdata',
            name='min_doc_and_clearance',
        ),
        migrations.RemoveField(
            model_name='parameterdata',
            name='min_duty_tax',
        ),
        migrations.RemoveField(
            model_name='parameterdata',
            name='min_export_handling',
        ),
        migrations.RemoveField(
            model_name='parameterdata',
            name='min_ground_handling',
        ),
        migrations.RemoveField(
            model_name='parameterdata',
            name='min_handling_charge',
        ),
        migrations.RemoveField(
            model_name='parameterdata',
            name='min_tax_handling_charge',
        ),
        migrations.RemoveField(
            model_name='parameterdata',
            name='min_warehouse_charge',
        ),
        migrations.RemoveField(
            model_name='parameterdata',
            name='price_airfreight_import_handling',
        ),
        migrations.RemoveField(
            model_name='parameterdata',
            name='price_cartage_and_warehouse_charge',
        ),
        migrations.RemoveField(
            model_name='parameterdata',
            name='price_delivery',
        ),
        migrations.RemoveField(
            model_name='parameterdata',
            name='price_doc_and_clearance',
        ),
        migrations.RemoveField(
            model_name='parameterdata',
            name='price_duty_tax',
        ),
        migrations.RemoveField(
            model_name='parameterdata',
            name='price_export_handling',
        ),
        migrations.RemoveField(
            model_name='parameterdata',
            name='price_ground_handling',
        ),
        migrations.RemoveField(
            model_name='parameterdata',
            name='price_handling_charge',
        ),
        migrations.RemoveField(
            model_name='parameterdata',
            name='price_tax_handling_charge',
        ),
        migrations.RemoveField(
            model_name='parameterdata',
            name='price_warehouse_charge',
        ),
        migrations.CreateModel(
            name='ParameterDataBl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_param', models.CharField(blank=True, choices=[('0', 'NonAktif'), ('1', 'Aktif')], default=0, max_length=20, null=True)),
                ('tgl_aktif_param', models.DateField(blank=True, null=True)),
                ('min_airfreight_import_handling', models.FloatField(blank=True, null=True)),
                ('max_airfreight_import_handling', models.FloatField(blank=True, null=True)),
                ('price_airfreight_import_handling', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('min_cartage_and_warehouse_charge', models.FloatField(blank=True, null=True)),
                ('max_cartage_and_warehouse_charge', models.FloatField(blank=True, null=True)),
                ('price_cartage_and_warehouse_charge', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('min_export_handling', models.FloatField(blank=True, null=True)),
                ('max_export_handling', models.FloatField(blank=True, null=True)),
                ('price_export_handling', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('airfreight_sin_dps_dil', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('min_doc_and_clearance', models.FloatField(blank=True, null=True)),
                ('max_doc_and_clearance', models.FloatField(blank=True, null=True)),
                ('price_doc_and_clearance', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('min_ground_handling', models.FloatField(blank=True, null=True)),
                ('max_ground_handling', models.FloatField(blank=True, null=True)),
                ('price_ground_handling', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('min_warehouse_charge', models.FloatField(blank=True, null=True)),
                ('max_warehouse_charge', models.FloatField(blank=True, null=True)),
                ('price_warehouse_charge', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('min_handling_charge', models.FloatField(blank=True, null=True)),
                ('max_handling_charge', models.FloatField(blank=True, null=True)),
                ('price_handling_charge', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('min_delivery', models.FloatField(blank=True, null=True)),
                ('max_delivery', models.FloatField(blank=True, null=True)),
                ('price_delivery', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('min_duty_tax', models.FloatField(blank=True, null=True)),
                ('max_duty_tax', models.FloatField(blank=True, null=True)),
                ('price_duty_tax', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('min_tax_handling_charge', models.FloatField(blank=True, null=True)),
                ('max_tax_handling_charge', models.FloatField(blank=True, null=True)),
                ('price_tax_handling_charge', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('cu', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cu_parambl', to=settings.AUTH_USER_MODEL)),
                ('nilai_kurs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.kurs')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.produk')),
            ],
            options={
                'verbose_name': 'ParameterDataBl',
                'verbose_name_plural': 'ParameterDataBl',
                'db_table': 'paramdatabl',
            },
        ),
    ]
