# Generated by Django 4.0.2 on 2022-10-11 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0035_remove_parameterdata_airfreight_sin_dps_dil_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_invoice', models.DateField()),
                ('no_invoice', models.IntegerField(blank=True, null=True)),
                ('qty', models.IntegerField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('price_airfreight', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('price_insurance_security_surcharge', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('price_fuel_surcharge', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('price_import_handling_charges', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('price_gst_zero_rated', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('price_storage_at_cost', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('price_pjkp2u_sin_dps_at_cost', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('price_storage_mcl_e_0389249_at_cost', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('price_pjkp2u_dps_dil_at_cost', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('price_airfreight_charges', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('price_overweight_charges_surcharge', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('price_awb_fee', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('price_handling_charges', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('price_ground_handling', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('price_forklift_for_heavy_cargo', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('price_custom_clearance', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('price_delivey_to_hera', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('price_akses_bandara_inspeksi', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('price_handling_fee', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('price_admin_fee', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('price_fee_collection', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('cu', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cu_job', to=settings.AUTH_USER_MODEL)),
                ('nilai_kurs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.kurs')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.produk')),
            ],
            options={
                'verbose_name': 'job',
                'db_table': 'job',
            },
        ),
        migrations.AddField(
            model_name='transaksi',
            name='no_pekerjaan',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Jual',
        ),
        migrations.AddField(
            model_name='job',
            name='transaksi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.transaksi'),
        ),
        migrations.AddField(
            model_name='job',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.jasapengiriman'),
        ),
    ]
