# Generated by Django 4.0.2 on 2022-10-11 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0036_job_transaksi_no_pekerjaan_delete_jual_job_transaksi_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='price_admin_fee',
            new_name='admin_fee',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='price_airfreight',
            new_name='airfreight',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='price_airfreight_charges',
            new_name='akses_bandara_inspeksi',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='price_akses_bandara_inspeksi',
            new_name='awb_fee',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='price_awb_fee',
            new_name='custom_clearance',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='price_custom_clearance',
            new_name='delivey_to_hera',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='price_delivey_to_hera',
            new_name='fee_collection',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='price_fee_collection',
            new_name='forklift_for_heavy_cargo',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='price_forklift_for_heavy_cargo',
            new_name='fuel_surcharge',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='price_fuel_surcharge',
            new_name='ground_handling',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='price_ground_handling',
            new_name='gst_zero_rated',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='price_gst_zero_rated',
            new_name='handling_charges',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='price_handling_charges',
            new_name='handling_fee',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='price_handling_fee',
            new_name='import_handling_charges',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='price_import_handling_charges',
            new_name='insurance_security_surcharge',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='price_insurance_security_surcharge',
            new_name='overweight_charges_surcharge',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='price_overweight_charges_surcharge',
            new_name='pjkp2u_dps_dil_at_cost',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='price_pjkp2u_dps_dil_at_cost',
            new_name='pjkp2u_sin_dps_at_cost',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='price_pjkp2u_sin_dps_at_cost',
            new_name='storage_at_cost',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='price_storage_at_cost',
            new_name='storage_mcl_e_0389249_at_cost',
        ),
        migrations.RemoveField(
            model_name='job',
            name='price_storage_mcl_e_0389249_at_cost',
        ),
    ]
