# Generated by Django 4.0.2 on 2022-10-13 22:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0037_rename_price_admin_fee_job_admin_fee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('0', 'NonAktif'), ('1', 'Aktif')], max_length=10, null=True)),
                ('mdate', models.DateTimeField(auto_now=True)),
                ('cu', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cu_cd', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'commodity',
            },
        ),
    ]
