# Generated by Django 4.0.2 on 2022-10-13 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0038_commodity'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaksi',
            name='commodity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.commodity'),
        ),
    ]
