# Generated by Django 4.0.2 on 2022-10-14 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0040_remove_job_products_transaksi_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='weight',
        ),
        migrations.AddField(
            model_name='transaksi',
            name='qty',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaksi',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
