# Generated by Django 4.0.2 on 2022-10-14 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0043_alter_produk_kurs_destinations_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produk',
            old_name='destinations_vendor',
            new_name='through_vendor',
        ),
    ]
