# Generated by Django 4.0.2 on 2022-10-14 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0044_rename_destinations_vendor_produk_through_vendor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produk',
            name='locations_vendor',
        ),
        migrations.AddField(
            model_name='produk',
            name='destinations_vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destinatioin_v3', to='products.jasapengiriman'),
        ),
        migrations.AlterField(
            model_name='produk',
            name='through_vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Through_v2', to='products.jasapengiriman'),
        ),
    ]
