# Generated by Django 4.0.2 on 2022-10-15 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0045_remove_produk_locations_vendor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='status_job',
            field=models.CharField(blank=True, choices=[('0', 'NonAktif'), ('1', 'Aktif')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='tanggal_status',
            field=models.DateField(blank=True, null=True),
        ),
    ]
