# Generated by Django 4.0.2 on 2022-10-16 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0047_job_cu_update_alter_job_status_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='re_export_shipment_one',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='re_export_shipment_one_pcs',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='re_export_shipment_one_qty',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='re_export_shipment_pcs',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='re_export_shipment_qty',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='re_export_shipment_two',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
