# Generated by Django 4.0.2 on 2022-10-16 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0048_job_re_export_shipment_one_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='re_export_shipment_pcs',
            new_name='re_export_shipment_two_pcs',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='re_export_shipment_qty',
            new_name='re_export_shipment_two_qty',
        ),
    ]
