# Generated by Django 4.0.2 on 2022-10-16 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0050_remove_job_re_export_shipment_one_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameterdatabl',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.jasapengiriman'),
        ),
    ]
