# Generated by Django 4.0.2 on 2022-10-16 21:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0051_parameterdatabl_vendor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cartage_warehouse_charge_one', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('cartage_warehouse_charge_two', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('airfreight_sl', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('doc_clearance', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('ground_handling', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('warehouse_charge', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('handling_charge', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('delivery', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('duty_tax', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('tax_handling_charge', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('cu', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cu_sale', to=settings.AUTH_USER_MODEL)),
                ('trans', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.transaksi')),
            ],
            options={
                'db_table': 'sale',
            },
        ),
    ]
