# Generated by Django 4.0.2 on 2022-10-17 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0052_sale'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='airfreight_sl',
            new_name='airfreight_one',
        ),
        migrations.AddField(
            model_name='sale',
            name='airfreight_two',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
    ]
