# Generated by Django 4.0.2 on 2022-10-17 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0053_rename_airfreight_sl_sale_airfreight_one_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.jasapengiriman'),
        ),
    ]
