# Generated by Django 4.0.2 on 2022-10-17 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0054_sale_vendor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='vendor',
        ),
        migrations.AddField(
            model_name='sale',
            name='prod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.parameterdatabl'),
        ),
    ]
