# Generated by Django 4.0.2 on 2022-10-17 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0055_remove_sale_vendor_sale_prod'),
    ]

    operations = [
        migrations.AddField(
            model_name='produk',
            name='jenis_produk',
            field=models.CharField(blank=True, choices=[('1', 'Airfreight'), ('2', 'Seafreight')], max_length=20, null=True),
        ),
    ]
