# Generated by Django 4.0.2 on 2022-11-06 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0058_parameterdatabl_max_airfreight_sin_dps_dil_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produk',
            name='jumlah_vendor',
            field=models.CharField(choices=[('1', 'SATU'), ('2', 'DUA'), ('3', 'TIGA')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='produk',
            name='kurs_origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='origin_kurs', to='products.kurs'),
        ),
        migrations.AlterField(
            model_name='produk',
            name='kurs_through',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='origin_trough', to='products.kurs'),
        ),
        migrations.AlterField(
            model_name='produk',
            name='origin_vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='origin_v1', to='products.jasapengiriman'),
        ),
        migrations.AlterField(
            model_name='produk',
            name='point_dua',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='point_dua', to='products.negara'),
        ),
        migrations.AlterField(
            model_name='produk',
            name='point_satu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='point_satu', to='products.negara'),
        ),
        migrations.AlterField(
            model_name='produk',
            name='through_vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Through_v2', to='products.jasapengiriman'),
        ),
    ]
