# Generated by Django 4.0.2 on 2022-11-06 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0059_alter_produk_kurs_origin_alter_produk_kurs_through_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produk',
            name='jenis_vendor',
            field=models.CharField(choices=[('1', 'SATU'), ('2', 'DUA'), ('3', 'TIGA')], max_length=20, null=True),
        ),
    ]
