# Generated by Django 4.0.2 on 2022-11-06 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0060_produk_jenis_vendor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produk',
            old_name='jenis_vendor',
            new_name='jumlah_vendor',
        ),
    ]
