# Generated by Django 4.0.2 on 2022-11-09 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0060_negara_cu'),
    ]

    operations = [
        migrations.AddField(
            model_name='negara',
            name='nama_kota',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
