# Generated by Django 4.0.2 on 2022-11-11 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0061_negara_nama_kota'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameterdata',
            name='max_airfreight',
        ),
        migrations.RemoveField(
            model_name='parameterdata',
            name='price_high_airfreight',
        ),
        migrations.AddField(
            model_name='job',
            name='agent_fee',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Wastila belanda', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='consignee',
            field=models.CharField(blank=True, help_text='Gasti asih caraka', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='custom_learance_fee_handling',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Wastila belanda', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='delivery',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Wastila belanda', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='emergency_situation',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='DHL', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='express_wordwide_nondoc',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='DHL', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='fuel_surcharge_dhl',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='DHL', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='heavy_weight_surcharge',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Wastila belanda', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='paking',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Gasti asih caraka', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='pcs',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Gasti asih caraka', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Gasti asih caraka', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='parameterdata',
            name='j_vendor',
            field=models.CharField(blank=True, choices=[('1', 'SATU'), ('2', 'DUA'), ('3', 'TIGA')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='parameterdata',
            name='min_agent_fee',
            field=models.FloatField(blank=True, help_text='Wastila Belanda', null=True),
        ),
        migrations.AddField(
            model_name='parameterdata',
            name='min_custom_learance_fee_handling',
            field=models.FloatField(blank=True, help_text='Wastila Belanda', null=True),
        ),
        migrations.AddField(
            model_name='parameterdata',
            name='min_delivery',
            field=models.FloatField(blank=True, help_text='Wastila Belanda', null=True),
        ),
        migrations.AddField(
            model_name='parameterdata',
            name='min_emergency_situation',
            field=models.FloatField(blank=True, help_text='DHl', null=True),
        ),
        migrations.AddField(
            model_name='parameterdata',
            name='min_express_wordwide_nondoc',
            field=models.FloatField(blank=True, help_text='DHl', null=True),
        ),
        migrations.AddField(
            model_name='parameterdata',
            name='min_fuel_surcharge_dhl',
            field=models.FloatField(blank=True, help_text='DHl', null=True),
        ),
        migrations.AddField(
            model_name='parameterdata',
            name='min_heavy_weight_surcharge',
            field=models.FloatField(blank=True, help_text='Wastila Belanda', null=True),
        ),
        migrations.AddField(
            model_name='parameterdata',
            name='min_paking',
            field=models.FloatField(blank=True, help_text='Gasti asih caraka', null=True),
        ),
        migrations.AddField(
            model_name='parameterdata',
            name='min_pcs',
            field=models.FloatField(blank=True, help_text='Gasti asih caraka', null=True),
        ),
        migrations.AddField(
            model_name='parameterdata',
            name='min_weight',
            field=models.FloatField(blank=True, help_text='Gasti asih caraka', null=True),
        ),
        migrations.AddField(
            model_name='parameterdata',
            name='price_agent_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Wastila Belanda', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='parameterdata',
            name='price_custom_learance_fee_handling',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Wastila Belanda', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='parameterdata',
            name='price_delivery',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Wastila Belanda', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='parameterdata',
            name='price_emergency_situation',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='DHl', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='parameterdata',
            name='price_express_wordwide_nondoc',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='DHl', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='parameterdata',
            name='price_fuel_surcharge_dhl',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='DHl', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='parameterdata',
            name='price_heavy_weight_surcharge',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Wastila Belanda', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='parameterdata',
            name='price_high_agent_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Wastila Belanda', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='parameterdata',
            name='price_high_custom_learance_fee_handling',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Wastila Belanda', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='parameterdata',
            name='price_high_delivery',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Wastila Belanda', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='parameterdata',
            name='price_high_emergency_situation',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='DHl', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='parameterdata',
            name='price_high_express_wordwide_nondoc',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='DHl', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='parameterdata',
            name='price_high_fuel_surcharge_dhl',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='DHl', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='parameterdata',
            name='price_high_heavy_weight_surcharge',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Wastila Belanda', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='parameterdata',
            name='price_high_paking',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Gasti Asih caraka', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='parameterdata',
            name='price_high_pcs',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Gasti Asih caraka', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='parameterdata',
            name='price_high_weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Gasti Asih caraka', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='parameterdata',
            name='price_paking',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Gasti Asih caraka', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='parameterdata',
            name='price_pcs',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Gasti Asih caraka', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='parameterdata',
            name='price_weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Gasti Asih caraka', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='admin_fee',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Dili', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='airfreight',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Freight', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='akses_bandara_inspeksi',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Dili', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='awb_fee',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Solid', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='custom_clearance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Dili', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='delivey_to_hera',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Dili', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='fee_collection',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Dili', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='forklift_for_heavy_cargo',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Dili', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='fuel_surcharge',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Freight', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='ground_handling',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Dili', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='gst_zero_rated',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Freight', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='handling_charges',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Freight', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='handling_fee',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Dili', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='import_handling_charges',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Freight', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='insurance_security_surcharge',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Freight', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='overweight_charges_surcharge',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Solid', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='pjkp2u_dps_dil_at_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Solid', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='pjkp2u_sin_dps_at_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Solid', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='storage_at_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Solid', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='storage_mcl_e_0389249_at_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Solid', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='parameterdata',
            name='nilai_kurs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.kurs'),
        ),
    ]
