# Generated by Django 4.0.2 on 2022-11-14 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0062_remove_parameterdata_max_airfreight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='no_invoice',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
