# Generated by Django 4.0.2 on 2022-11-15 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0063_alter_job_no_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='no_invoice_sl_2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='no_invoice_sl_3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
