# Generated by Django 4.0.2 on 2022-11-15 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0064_job_no_invoice_sl_2_job_no_invoice_sl_3'),
    ]

    operations = [
        migrations.AddField(
            model_name='jasapengiriman',
            name='nilai_kurs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.kurs'),
        ),
        migrations.AddField(
            model_name='kurs',
            name='simbol',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
