# Generated by Django 4.0.2 on 2022-11-11 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0065_job_consignee_job_paking_job_pcs_job_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='agent_fee',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Wastila belanda', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='custom_learance_fee_handling',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Wastila belanda', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='delivery',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Wastila belanda', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='heavy_weight_surcharge',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Wastila belanda', max_digits=12, null=True),
        ),
    ]
