# Generated by Django 4.0.2 on 2022-11-16 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0065_jasapengiriman_nilai_kurs_kurs_simbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaksi',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
