# Generated by Django 4.0.2 on 2022-11-11 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0066_job_agent_fee_job_custom_learance_fee_handling_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='emergency_situation',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='DHL', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='express_wordwide_nondoc',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='DHL', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='fuel_surcharge_dhl',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='DHL', max_digits=12, null=True),
        ),
    ]
