# Generated by Django 4.0.2 on 2022-11-16 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0066_alter_transaksi_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='consignee',
        ),
        migrations.AddField(
            model_name='job',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Gasti asih caraka', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='biaya_peb',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='ANTAR LAPAN', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='blfee',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='ANTAR LAPAN', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='cbm',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='ANTAR LAPAN', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='transit_charge',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Lintas Negara', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='transportations_charge',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Lintas Negara', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='twentyft',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='ANTAR LAPAN', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='produk',
            name='jenis_produk',
            field=models.CharField(blank=True, choices=[('1', 'Airfreight'), ('2', 'Seafreight'), ('3', 'Landfreught')], max_length=20, null=True),
        ),
    ]
