# Generated by Django 4.0.2 on 2022-11-17 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0067_remove_job_consignee_job_amount_job_biaya_peb_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='jenis',
            field=models.CharField(blank=True, choices=[('1', 'Airfreight'), ('2', 'Seafreight'), ('3', 'Landfreught')], max_length=20, null=True),
        ),
    ]
