# Generated by Django 4.0.2 on 2022-11-11 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0070_alter_parameterdata_j_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameterdata',
            name='nilai_kurs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.kurs'),
        ),
    ]
