# Generated by Django 4.0.2 on 2022-11-12 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0071_alter_parameterdata_nilai_kurs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameterdatabl',
            name='nilai_kurs',
        ),
    ]
