# Generated by Django 4.0.2 on 2022-11-14 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0072_remove_parameterdatabl_nilai_kurs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='no_invoice',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
