# Generated by Django 4.0.2 on 2022-11-15 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0075_jasapengiriman_nilai_kurs'),
    ]

    operations = [
        migrations.AddField(
            model_name='kurs',
            name='simbol',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
