# Generated by Django 4.0.2 on 2022-11-17 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0068_job_jenis'),
        ('products', '0077_alter_transaksi_weight'),
    ]

    operations = [
    ]
