# Generated by Django 4.0.2 on 2022-11-23 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0080_parameterdata_j_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='status_duty',
            field=models.CharField(blank=True, choices=[('', '--Piih--'), ('1', 'Tidak'), ('2', 'Ada')], max_length=10, null=True),
        ),
    ]
