# Generated by Django 4.0.2 on 2022-11-23 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0081_sale_status_duty'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='no_invoice_sl_2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='no_invoice_sl_3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='no_invoice',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
