# Generated by Django 4.0.2 on 2022-11-29 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0082_job_no_invoice_sl_2_job_no_invoice_sl_3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='status_sale',
            field=models.CharField(blank=True, choices=[('', ''), ('1', 'Done')], max_length=50, null=True),
        ),
    ]
