# Generated by Django 4.0.2 on 2022-12-01 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0085_alter_sale_tgl_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameterdata',
            name='min_agent_fee',
            field=models.FloatField(blank=True, help_text='Wastila Belanda', null=True),
        ),
        migrations.AddField(
            model_name='parameterdata',
            name='min_custom_learance_fee_handling',
            field=models.FloatField(blank=True, help_text='Wastila Belanda', null=True),
        ),
        migrations.AddField(
            model_name='parameterdata',
            name='min_delivery',
            field=models.FloatField(blank=True, help_text='Wastila Belanda', null=True),
        ),
        migrations.AddField(
            model_name='parameterdata',
            name='min_emergency_situation',
            field=models.FloatField(blank=True, help_text='DHl', null=True),
        ),
        migrations.AddField(
            model_name='parameterdata',
            name='min_express_wordwide_nondoc',
            field=models.FloatField(blank=True, help_text='DHl', null=True),
        ),
        migrations.AddField(
            model_name='parameterdata',
            name='min_fuel_surcharge_dhl',
            field=models.FloatField(blank=True, help_text='DHl', null=True),
        ),
        migrations.AddField(
            model_name='parameterdata',
            name='min_heavy_weight_surcharge',
            field=models.FloatField(blank=True, help_text='Wastila Belanda', null=True),
        ),
        migrations.AddField(
            model_name='parameterdata',
            name='min_paking',
            field=models.FloatField(blank=True, help_text='Gasti asih caraka', null=True),
        ),
        migrations.AddField(
            model_name='parameterdata',
            name='min_pcs',
            field=models.FloatField(blank=True, help_text='Gasti asih caraka', null=True),
        ),
        migrations.AddField(
            model_name='parameterdata',
            name='min_weight',
            field=models.FloatField(blank=True, help_text='Gasti asih caraka', null=True),
        ),
        migrations.AddField(
            model_name='parameterdata',
            name='price_agent_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Wastila Belanda', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='parameterdata',
            name='price_custom_learance_fee_handling',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Wastila Belanda', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='parameterdata',
            name='price_delivery',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Wastila Belanda', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='parameterdata',
            name='price_emergency_situation',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='DHl', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='parameterdata',
            name='price_express_wordwide_nondoc',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='DHl', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='parameterdata',
            name='price_fuel_surcharge_dhl',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='DHl', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='parameterdata',
            name='price_heavy_weight_surcharge',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Wastila Belanda', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='parameterdata',
            name='price_high_agent_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Wastila Belanda', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='parameterdata',
            name='price_high_custom_learance_fee_handling',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Wastila Belanda', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='parameterdata',
            name='price_high_delivery',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Wastila Belanda', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='parameterdata',
            name='price_high_emergency_situation',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='DHl', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='parameterdata',
            name='price_high_express_wordwide_nondoc',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='DHl', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='parameterdata',
            name='price_high_fuel_surcharge_dhl',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='DHl', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='parameterdata',
            name='price_high_heavy_weight_surcharge',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Wastila Belanda', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='parameterdata',
            name='price_high_paking',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Gasti Asih caraka', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='parameterdata',
            name='price_high_pcs',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Gasti Asih caraka', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='parameterdata',
            name='price_high_weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Gasti Asih caraka', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='parameterdata',
            name='price_paking',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Gasti Asih caraka', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='parameterdata',
            name='price_pcs',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Gasti Asih caraka', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='parameterdata',
            name='price_weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Gasti Asih caraka', max_digits=12, null=True),
        ),
    ]
