# Generated by Django 4.0.2 on 2022-12-01 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0086_parameterdata_min_agent_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='delivey_to',
            field=models.CharField(blank=True, choices=[('', '--- SELECT ---'), ('1', 'Hera'), ('2', 'Okusi'), ('3', 'Betano')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='delivey_to_betano',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='delivey_to_okusi',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
    ]
