# Generated by Django 4.0.2 on 2022-12-05 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0087_job_delivey_to_job_delivey_to_betano_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jasapengiriman',
            name='singkatan',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='delivey_to',
            field=models.CharField(blank=True, choices=[('', '--SELECT--'), ('3', 'Hera'), ('4', 'Okusi'), ('5', 'Betano')], max_length=10, null=True),
        ),
    ]
