# Generated by Django 4.0.2 on 2022-12-06 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0088_jasapengiriman_singkatan_alter_job_delivey_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameterdata',
            name='min_paking',
        ),
        migrations.RemoveField(
            model_name='parameterdata',
            name='price_high_paking',
        ),
        migrations.RemoveField(
            model_name='parameterdata',
            name='price_paking',
        ),
        migrations.AddField(
            model_name='parameterdata',
            name='min_handling',
            field=models.FloatField(blank=True, default=0, help_text='Gasti asih caraka', null=True),
        ),
        migrations.AddField(
            model_name='parameterdata',
            name='min_transportation_charge',
            field=models.FloatField(blank=True, default=0, help_text='Gasti asih caraka', null=True),
        ),
        migrations.AddField(
            model_name='parameterdata',
            name='price_handling',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Gasti Asih caraka', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='parameterdata',
            name='price_high_handling',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Gasti Asih caraka', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='parameterdata',
            name='price_high_transportation_charge',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Gasti Asih caraka', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='parameterdata',
            name='price_transportation_charge',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Gasti Asih caraka', max_digits=12, null=True),
        ),
    ]
