# Generated by Django 4.0.2 on 2022-12-06 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0089_remove_parameterdata_min_paking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='agent_fee',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Wastila belanda', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Gasti asih caraka', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='biaya_peb',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='ANTAR LAPAN', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='blfee',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='ANTAR LAPAN', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='cbm',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='ANTAR LAPAN', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='custom_learance_fee_handling',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Wastila belanda', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='delivery',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Wastila belanda', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='emergency_situation',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='DHL', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='express_wordwide_nondoc',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='DHL', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='fuel_surcharge_dhl',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='DHL', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='heavy_weight_surcharge',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Wastila belanda', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='jenis',
            field=models.CharField(blank=True, choices=[('1', 'Airfreight'), ('2', 'Seafreight')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='paking',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Gasti asih caraka', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='pcs',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Gasti asih caraka', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='transit_charge',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Lintas Negara', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='transportations_charge',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Lintas Negara', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='twentyft',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='ANTAR LAPAN', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Gasti asih caraka', max_digits=12, null=True),
        ),
    ]
