# Generated by Django 4.0.2 on 2022-12-06 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0090_job_agent_fee_job_amount_job_biaya_peb_job_blfee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='transportation_charge',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Gasti asih caraka', max_digits=12, null=True),
        ),
    ]
