# Generated by Django 4.0.2 on 2022-12-07 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0091_job_transportation_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='negara',
            name='nama_kota',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
