# Generated by Django 4.0.2 on 2022-12-15 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0093_sale_eta_sale_etd_sale_insurance_sale_shipment_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='airfreight_four',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='airfreight_tree',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='cartage_warehouse_charge_four',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='cartage_warehouse_charge_tree',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='total_shipment',
            field=models.CharField(blank=True, choices=[('', '--SELECT--'), ('6', '1'), ('7', '2'), ('8', '3'), ('9', '4')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='transaksi',
            name='re_export_shipment_four',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='transaksi',
            name='re_export_shipment_four_pcs',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='transaksi',
            name='re_export_shipment_four_qty',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='transaksi',
            name='re_export_shipment_tree',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='transaksi',
            name='re_export_shipment_tree_pcs',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='transaksi',
            name='re_export_shipment_tree_qty',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
    ]
