# Generated by Django 4.0.2 on 2022-12-15 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0095_sale_price_cartage_warehouse_charge_four_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='awb',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='price_freight',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
    ]
