# Generated by Django 4.0.2 on 2022-12-16 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0098_refcustomer'),
    ]

    operations = [
        migrations.AddField(
            model_name='refcustomer',
            name='jumlahreffcs',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='refcustomer',
            name='jenis',
            field=models.CharField(blank=True, choices=[('1', 'REFF & CUSTOMER'), ('2', ' REFF'), ('3', 'Customer')], max_length=20, null=True),
        ),
    ]
