# Generated by Django 4.0.2 on 2022-12-16 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0099_refcustomer_jumlahreffcs_alter_refcustomer_jenis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refcustomer',
            name='jenis',
        ),
    ]
