# Generated by Django 4.0.2 on 2022-12-16 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0100_remove_refcustomer_jenis'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='kurs_duty',
            field=models.CharField(blank=True, choices=[('1', '€'), ('2', '$'), ('3', 'Rp')], default=1, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='refcustomer',
            name='jumlahreff',
            field=models.CharField(blank=True, choices=[('', '--SELECT--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='refcustomer',
            name='jumlahreffcs',
            field=models.CharField(blank=True, choices=[('', '--SELECT--'), ('11', '1'), ('12', '2'), ('13', '3'), ('14', '4'), ('15', '5'), ('16', '6'), ('17', '7'), ('18', '8'), ('19', '9'), ('20', '10')], max_length=20, null=True),
        ),
    ]
