# Generated by Django 4.0.2 on 2022-12-21 01:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0101_sale_kurs_duty_alter_refcustomer_jumlahreff_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddresInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100, null=True)),
                ('alamat', models.CharField(max_length=100, null=True)),
                ('telepon', models.CharField(max_length=20, null=True)),
                ('status', models.CharField(blank=True, choices=[('0', 'NonAktif'), ('1', 'Aktif')], default=0, max_length=20, null=True)),
                ('cu', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cu_addI', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AddresInvoice',
                'db_table': 'addresinvoice',
            },
        ),
        migrations.CreateModel(
            name='ConsigneInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100, null=True)),
                ('alamat', models.CharField(max_length=100, null=True)),
                ('kota', models.CharField(max_length=100, null=True)),
                ('telepon', models.CharField(max_length=20, null=True)),
                ('status', models.CharField(blank=True, choices=[('0', 'NonAktif'), ('1', 'Aktif')], default=0, max_length=20, null=True)),
                ('cu', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cu_csg', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ConsigneInvoice',
                'db_table': 'Consigneinvoice',
            },
        ),
        migrations.CreateModel(
            name='DdpInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_ddp', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(blank=True, choices=[('0', 'NonAktif'), ('1', 'Aktif')], default=0, max_length=20, null=True)),
                ('cu', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cu_ddp', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'DdpInvoice',
                'db_table': 'DdpInvoice',
            },
        ),
        migrations.CreateModel(
            name='TermInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_term', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(blank=True, choices=[('0', 'NonAktif'), ('1', 'Aktif')], default=0, max_length=20, null=True)),
                ('cu', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cu_term', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'TermInvoice',
                'db_table': 'TermInvoice',
            },
        ),
        migrations.CreateModel(
            name='ShipperInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100, null=True)),
                ('alamat', models.CharField(max_length=100, null=True)),
                ('kota', models.CharField(max_length=100, null=True)),
                ('telepon', models.CharField(max_length=20, null=True)),
                ('status', models.CharField(blank=True, choices=[('0', 'NonAktif'), ('1', 'Aktif')], default=0, max_length=20, null=True)),
                ('cu', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cu_ssp', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ShipperInvoice',
                'db_table': 'shipersinvoice',
            },
        ),
        migrations.CreateModel(
            name='PicInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_pic', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(blank=True, choices=[('0', 'NonAktif'), ('1', 'Aktif')], default=0, max_length=20, null=True)),
                ('cu', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cu_pic', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PicInvoice',
                'db_table': 'PicInvoice',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_header', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inv_01', to='products.addresinvoice')),
                ('consignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.consigneinvoice', verbose_name='inv_03')),
                ('ddp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.ddpinvoice', verbose_name='inv_04')),
                ('pic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.picinvoice', verbose_name='inv_05')),
                ('shipper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.shipperinvoice', verbose_name='inv_02')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.terminvoice', verbose_name='inv_03')),
            ],
            options={
                'verbose_name': 'Invoice',
                'db_table': 'Invoice',
            },
        ),
        migrations.AddField(
            model_name='sale',
            name='inv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.invoice'),
        ),
    ]
