# Generated by Django 4.0.2 on 2022-12-22 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0103_alter_consigneinvoice_alamat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='ddp',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='pic',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='term',
        ),
        migrations.AddField(
            model_name='sale',
            name='ddp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.ddpinvoice', verbose_name='DDP'),
        ),
        migrations.AddField(
            model_name='sale',
            name='pic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.picinvoice', verbose_name='PIC'),
        ),
        migrations.AddField(
            model_name='sale',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.terminvoice', verbose_name='Term'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='consignee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.consigneinvoice', verbose_name='Consigne'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='shipper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.shipperinvoice', verbose_name='Shipper'),
        ),
    ]
