# Generated by Django 4.0.2 on 2022-12-24 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0106_rename_re_export_shipment_four_transaksi_re_export_shipment_delapanbelas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jasapengiriman',
            name='nilai_kurs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.kurs'),
        ),
    ]
