# Generated by Django 4.0.2 on 2022-12-25 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0107_jasapengiriman_nilai_kurs'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaksi',
            name='re_export_shipment_four',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='transaksi',
            name='re_export_shipment_four_pcs',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='transaksi',
            name='re_export_shipment_four_qty',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total_shipment',
            field=models.CharField(blank=True, choices=[('', '--SELECT--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18')], max_length=50, null=True),
        ),
    ]
