# Generated by Django 4.0.2 on 2022-12-25 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0108_transaksi_re_export_shipment_four_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuInputSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_form', models.CharField(choices=[('1', 'Form1'), ('2', 'Fom2')], max_length=50, verbose_name='Jenis Form')),
                ('repecking', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('pickup', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('freight_cost', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='Freight Cost')),
                ('overweight_charge', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='Overweight Charge')),
                ('insuranse_forms', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='Insurence')),
                ('cartage_warehouse_charge_satu', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('cartage_warehouse_charge_dua', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('cartage_warehouse_charge_tiga', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('cartage_warehouse_charge_empat', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('cartage_warehouse_charge_lima', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('cartage_warehouse_charge_enam', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('cartage_warehouse_charge_tujuh', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('cartage_warehouse_charge_delapan', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('cartage_warehouse_charge_sembilan', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('cartage_warehouse_charge_sepuluh', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('cartage_warehouse_charge_sebelas', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('cartage_warehouse_charge_duabelas', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('cartage_warehouse_charge_tigabelas', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('cartage_warehouse_charge_empatbelas', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('cartage_warehouse_charge_limabelas', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('cartage_warehouse_charge_enambelas', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('cartage_warehouse_charge_tujuhbelas', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('cartage_warehouse_charge_delapanbelas', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('cartage_warehouse_charge_sembilanbelas', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('cartage_warehouse_charge_duapuluh', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('price_cartage_warehouse_charge_satu', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('price_cartage_warehouse_charge_dua', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('price_cartage_warehouse_charge_tiga', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('price_cartage_warehouse_charge_empat', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('price_cartage_warehouse_charge_lima', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('price_cartage_warehouse_charge_enam', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('price_cartage_warehouse_charge_tujuh', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('price_cartage_warehouse_charge_delapan', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('price_cartage_warehouse_charge_sembilan', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('price_cartage_warehouse_charge_sepuluh', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('price_cartage_warehouse_charge_sebelas', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('price_cartage_warehouse_charge_duabelas', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('price_cartage_warehouse_charge_tigabelas', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('price_cartage_warehouse_charge_empatbelas', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('price_cartage_warehouse_charge_limabelas', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('price_cartage_warehouse_charge_enambelas', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('price_cartage_warehouse_charge_tujuhbelas', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('price_cartage_warehouse_charge_delapanbelas', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('price_cartage_warehouse_charge_sembilanbelas', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('price_cartage_warehouse_charge_daupuluh', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('airfreight_satu', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('airfreight_dua', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('airfreight_tiga', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('airfreight_empat', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('airfreight_lima', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('airfreight_enam', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('airfreight_tujuh', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('airfreight_delapan', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('airfreight_sembilan', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('airfreight_sepuluh', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('airfreight_sebelas', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('airfreight_duabelas', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('airfreight_tigabelas', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('airfreight_empatbelas', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('airfreight_limabelas', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('airfreight_enambelas', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('airfreight_tujuhbelas', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('airfreight_delapanbelas', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('airfreight_sembilanbelas', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('airfreight_duapuluh', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('re_export_shipment_satu', models.CharField(blank=True, max_length=30, null=True)),
                ('re_export_shipment_satu_pcs', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('re_export_shipment_satu_qty', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('re_export_shipment_dua', models.CharField(blank=True, max_length=30, null=True)),
                ('re_export_shipment_dua_pcs', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('re_export_shipment_dua_qty', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('re_export_shipment_tiga', models.CharField(blank=True, max_length=30, null=True)),
                ('re_export_shipment_tiga_pcs', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('re_export_shipment_tiga_qty', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('re_export_shipment_empat', models.CharField(blank=True, max_length=30, null=True)),
                ('re_export_shipment_empat_pcs', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('re_export_shipment_empat_qty', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('re_export_shipment_lima', models.CharField(blank=True, max_length=30, null=True)),
                ('re_export_shipment_lima_pcs', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('re_export_shipment_lima_qty', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('re_export_shipment_enam', models.CharField(blank=True, max_length=30, null=True)),
                ('re_export_shipment_enam_pcs', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('re_export_shipment_enam_qty', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('re_export_shipment_tujuh', models.CharField(blank=True, max_length=30, null=True)),
                ('re_export_shipment_tujuh_pcs', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('re_export_shipment_tujuh_qty', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('re_export_shipment_delapan', models.CharField(blank=True, max_length=30, null=True)),
                ('re_export_shipment_delapan_pcs', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('re_export_shipment_delapan_qty', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('re_export_shipment_sembilan', models.CharField(blank=True, max_length=30, null=True)),
                ('re_export_shipment_sembilan_pcs', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('re_export_shipment_sembilan_qty', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('re_export_shipment_sepuluh', models.CharField(blank=True, max_length=30, null=True)),
                ('re_export_shipment_sepuluh_pcs', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('re_export_shipment_sepuluh_qty', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('re_export_shipment_sebelas', models.CharField(blank=True, max_length=30, null=True)),
                ('re_export_shipment_sebelas_pcs', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('re_export_shipment_sebelas_qty', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('re_export_shipment_duabelas', models.CharField(blank=True, max_length=30, null=True)),
                ('re_export_shipment_duabelas_pcs', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('re_export_shipment_duabelas_qty', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('re_export_shipment_tigabelas', models.CharField(blank=True, max_length=30, null=True)),
                ('re_export_shipment_tigabelas_pcs', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('re_export_shipment_tigabelas_qty', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('re_export_shipment_empatbelas', models.CharField(blank=True, max_length=30, null=True)),
                ('re_export_shipment_empatbelas_pcs', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('re_export_shipment_empatbelas_qty', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('re_export_shipment_limabelas', models.CharField(blank=True, max_length=30, null=True)),
                ('re_export_shipment_limabelas_pcs', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('re_export_shipment_limabelas_qty', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('re_export_shipment_enambelas', models.CharField(blank=True, max_length=30, null=True)),
                ('re_export_shipment_enambelas_pcs', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('re_export_shipment_enambelas_qty', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('re_export_shipment_tujuhbelas', models.CharField(blank=True, max_length=30, null=True)),
                ('re_export_shipment_tujuhbelas_pcs', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('re_export_shipment_tujuhbelas_qty', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('re_export_shipment_delapanbelas', models.CharField(blank=True, max_length=30, null=True)),
                ('re_export_shipment_delapanbelas_pcs', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('re_export_shipment_delapanbelas_qty', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('re_export_shipment_sembilanbelas', models.CharField(blank=True, max_length=30, null=True)),
                ('re_export_shipment_sembilanbelas_pcs', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('re_export_shipment_sembilanbelas_qty', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('re_export_shipment_duapuluh', models.CharField(blank=True, max_length=30, null=True)),
                ('re_export_shipment_duapuluh_pcs', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('re_export_shipment_duapuluh_qty', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
            ],
            options={
                'db_table': 'MenuInputSale',
            },
        ),
        migrations.RemoveField(
            model_name='sale',
            name='airfreight_four',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='airfreight_one',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='airfreight_tree',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='airfreight_two',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='cartage_warehouse_charge_four',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='cartage_warehouse_charge_one',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='cartage_warehouse_charge_tree',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='cartage_warehouse_charge_two',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='price_cartage_warehouse_charge_four',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='price_cartage_warehouse_charge_one',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='price_cartage_warehouse_charge_tree',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='price_cartage_warehouse_charge_two',
        ),
        migrations.RemoveField(
            model_name='transaksi',
            name='re_export_shipment_delapanbelas',
        ),
        migrations.RemoveField(
            model_name='transaksi',
            name='re_export_shipment_delapanbelas_pcs',
        ),
        migrations.RemoveField(
            model_name='transaksi',
            name='re_export_shipment_delapanbelas_qty',
        ),
        migrations.RemoveField(
            model_name='transaksi',
            name='re_export_shipment_duabelas',
        ),
        migrations.RemoveField(
            model_name='transaksi',
            name='re_export_shipment_duabelas_pcs',
        ),
        migrations.RemoveField(
            model_name='transaksi',
            name='re_export_shipment_duabelas_qty',
        ),
        migrations.RemoveField(
            model_name='transaksi',
            name='re_export_shipment_duapuluh',
        ),
        migrations.RemoveField(
            model_name='transaksi',
            name='re_export_shipment_duapuluh_pcs',
        ),
        migrations.RemoveField(
            model_name='transaksi',
            name='re_export_shipment_duapuluh_qty',
        ),
        migrations.RemoveField(
            model_name='transaksi',
            name='re_export_shipment_eight',
        ),
        migrations.RemoveField(
            model_name='transaksi',
            name='re_export_shipment_eight_pcs',
        ),
        migrations.RemoveField(
            model_name='transaksi',
            name='re_export_shipment_eight_qty',
        ),
        migrations.RemoveField(
            model_name='transaksi',
            name='re_export_shipment_empatbelas',
        ),
        migrations.RemoveField(
            model_name='transaksi',
            name='re_export_shipment_empatbelas_pcs',
        ),
        migrations.RemoveField(
            model_name='transaksi',
            name='re_export_shipment_empatbelas_qty',
        ),
        migrations.RemoveField(
            model_name='transaksi',
            name='re_export_shipment_enambelas',
        ),
        migrations.RemoveField(
            model_name='transaksi',
            name='re_export_shipment_enambelas_pcs',
        ),
        migrations.RemoveField(
            model_name='transaksi',
            name='re_export_shipment_enambelas_qty',
        ),
        migrations.RemoveField(
            model_name='transaksi',
            name='re_export_shipment_five',
        ),
        migrations.RemoveField(
            model_name='transaksi',
            name='re_export_shipment_five_pcs',
        ),
        migrations.RemoveField(
            model_name='transaksi',
            name='re_export_shipment_five_qty',
        ),
        migrations.RemoveField(
            model_name='transaksi',
            name='re_export_shipment_four',
        ),
        migrations.RemoveField(
            model_name='transaksi',
            name='re_export_shipment_four_pcs',
        ),
        migrations.RemoveField(
            model_name='transaksi',
            name='re_export_shipment_four_qty',
        ),
        migrations.RemoveField(
            model_name='transaksi',
            name='re_export_shipment_limabelas',
        ),
        migrations.RemoveField(
            model_name='transaksi',
            name='re_export_shipment_limabelas_pcs',
        ),
        migrations.RemoveField(
            model_name='transaksi',
            name='re_export_shipment_limabelas_qty',
        ),
        migrations.RemoveField(
            model_name='transaksi',
            name='re_export_shipment_nine',
        ),
        migrations.RemoveField(
            model_name='transaksi',
            name='re_export_shipment_nine_pcs',
        ),
        migrations.RemoveField(
            model_name='transaksi',
            name='re_export_shipment_nine_qty',
        ),
        migrations.RemoveField(
            model_name='transaksi',
            name='re_export_shipment_one',
        ),
        migrations.RemoveField(
            model_name='transaksi',
            name='re_export_shipment_one_pcs',
        ),
        migrations.RemoveField(
            model_name='transaksi',
            name='re_export_shipment_one_qty',
        ),
        migrations.RemoveField(
            model_name='transaksi',
            name='re_export_shipment_sebelas',
        ),
        migrations.RemoveField(
            model_name='transaksi',
            name='re_export_shipment_sebelas_pcs',
        ),
        migrations.RemoveField(
            model_name='transaksi',
            name='re_export_shipment_sebelas_qty',
        ),
        migrations.RemoveField(
            model_name='transaksi',
            name='re_export_shipment_sembilanbelas',
        ),
        migrations.RemoveField(
            model_name='transaksi',
            name='re_export_shipment_sembilanbelas_pcs',
        ),
        migrations.RemoveField(
            model_name='transaksi',
            name='re_export_shipment_sembilanbelas_qty',
        ),
        migrations.RemoveField(
            model_name='transaksi',
            name='re_export_shipment_seven',
        ),
        migrations.RemoveField(
            model_name='transaksi',
            name='re_export_shipment_seven_pcs',
        ),
        migrations.RemoveField(
            model_name='transaksi',
            name='re_export_shipment_seven_qty',
        ),
        migrations.RemoveField(
            model_name='transaksi',
            name='re_export_shipment_six',
        ),
        migrations.RemoveField(
            model_name='transaksi',
            name='re_export_shipment_six_pcs',
        ),
        migrations.RemoveField(
            model_name='transaksi',
            name='re_export_shipment_six_qty',
        ),
        migrations.RemoveField(
            model_name='transaksi',
            name='re_export_shipment_ten',
        ),
        migrations.RemoveField(
            model_name='transaksi',
            name='re_export_shipment_ten_pcs',
        ),
        migrations.RemoveField(
            model_name='transaksi',
            name='re_export_shipment_ten_qty',
        ),
        migrations.RemoveField(
            model_name='transaksi',
            name='re_export_shipment_tigabelas',
        ),
        migrations.RemoveField(
            model_name='transaksi',
            name='re_export_shipment_tigabelas_pcs',
        ),
        migrations.RemoveField(
            model_name='transaksi',
            name='re_export_shipment_tigabelas_qty',
        ),
        migrations.RemoveField(
            model_name='transaksi',
            name='re_export_shipment_tree',
        ),
        migrations.RemoveField(
            model_name='transaksi',
            name='re_export_shipment_tree_pcs',
        ),
        migrations.RemoveField(
            model_name='transaksi',
            name='re_export_shipment_tree_qty',
        ),
        migrations.RemoveField(
            model_name='transaksi',
            name='re_export_shipment_tujuhbelas',
        ),
        migrations.RemoveField(
            model_name='transaksi',
            name='re_export_shipment_tujuhbelas_pcs',
        ),
        migrations.RemoveField(
            model_name='transaksi',
            name='re_export_shipment_tujuhbelas_qty',
        ),
        migrations.RemoveField(
            model_name='transaksi',
            name='re_export_shipment_two',
        ),
        migrations.RemoveField(
            model_name='transaksi',
            name='re_export_shipment_two_pcs',
        ),
        migrations.RemoveField(
            model_name='transaksi',
            name='re_export_shipment_two_qty',
        ),
        migrations.AddField(
            model_name='sale',
            name='formsale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.menuinputsale'),
        ),
    ]
