# Generated by Django 4.0.2 on 2022-12-25 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0109_menuinputsale_remove_sale_airfreight_four_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='total_shipment',
        ),
        migrations.AddField(
            model_name='menuinputsale',
            name='total_shipment',
            field=models.CharField(blank=True, choices=[('', '--SELECT--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18')], max_length=50, null=True),
        ),
    ]
