# Generated by Django 4.0.2 on 2022-12-25 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0110_remove_sale_total_shipment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='inv',
        ),
        migrations.AddField(
            model_name='sale',
            name='consigne',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.consigneinvoice'),
        ),
        migrations.AddField(
            model_name='sale',
            name='head_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.addresinvoice'),
        ),
        migrations.AddField(
            model_name='sale',
            name='shipper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.shipperinvoice'),
        ),
    ]
