# Generated by Django 4.0.2 on 2022-12-26 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0111_remove_sale_inv_sale_consigne_sale_head_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuinputsale',
            name='freight_cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='Freight Cost Price'),
        ),
        migrations.AddField(
            model_name='menuinputsale',
            name='freight_cost_qty',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='Freight Cost QTY'),
        ),
        migrations.AddField(
            model_name='menuinputsale',
            name='insuranse_nilai',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='Insurence Persen'),
        ),
        migrations.AddField(
            model_name='menuinputsale',
            name='overweight_charge_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='Overweight Charge Price'),
        ),
        migrations.AddField(
            model_name='menuinputsale',
            name='overweight_charge_qty',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='Overweight Charge QTY'),
        ),
        migrations.AddField(
            model_name='menuinputsale',
            name='pickup_qty',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='menuinputsale',
            name='repecking_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='menuinputsale',
            name='repecking_qty',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='menuinputsale',
            name='jenis_form',
            field=models.CharField(choices=[('', '--Select--'), ('100', 'Form1'), ('200', 'Fom2')], max_length=50, verbose_name='Jenis Form'),
        ),
    ]
