# Generated by Django 4.0.2 on 2022-12-26 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0113_menuinputsale_insuranse_pers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuinputsale',
            name='gross_weight',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='Gross Weight'),
        ),
        migrations.AddField(
            model_name='menuinputsale',
            name='nb_of_parcels',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='NB OF PARCE'),
        ),
    ]
