# Generated by Django 4.0.2 on 2022-10-14 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountsuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='alamat email'),
        ),
    ]
