# Generated by Django 4.0.2 on 2022-10-31 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_cabang_cu_remove_cabang_mdate_and_more'),
        ('core', '0002_alter_accountsuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cabang',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='val_cab', to='home.cabang'),
        ),
    ]
