# Generated by Django 4.0.2 on 2022-11-17 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0067_remove_job_consignee_job_amount_job_biaya_peb_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GastiAsih',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_angkutan', models.CharField(blank=True, choices=[('1', 'Airfreight'), ('2', 'Seafreight'), ('3', 'Landfreught')], max_length=20, null=True)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('destinations', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='des_gst', to='products.negara')),
                ('name_vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.jasapengiriman')),
                ('origin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='or_gst', to='products.negara')),
            ],
            options={
                'db_table': 'gastiasih',
            },
        ),
    ]
