# Generated by Django 4.0.2 on 2022-10-31 18:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cabang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50, null=True)),
                ('alamat', models.CharField(blank=True, max_length=250, null=True)),
                ('kota', models.CharField(blank=True, max_length=35, null=True)),
                ('telepon', models.CharField(blank=True, max_length=35, null=True)),
                ('kodepos', models.CharField(blank=True, max_length=7, null=True)),
                ('kode_cabang', models.IntegerField(null=True)),
                ('kepala_cabang', models.CharField(max_length=25, null=True)),
                ('adm_cabang', models.CharField(max_length=25, null=True)),
                ('singkatan', models.CharField(max_length=12, null=True)),
                ('kode_produk', models.CharField(max_length=2, null=True)),
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('mdate', models.DateTimeField(auto_now=True)),
                ('aktif', models.BooleanField(default=False)),
                ('cu', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('mu', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.cabang')),
            ],
            options={
                'verbose_name': 'Cabang',
                'verbose_name_plural': 'Cabang',
                'db_table': 'cabang',
            },
        ),
    ]
