# Generated by Django 4.0.2 on 2022-10-31 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cabang',
            name='cu',
        ),
        migrations.RemoveField(
            model_name='cabang',
            name='mdate',
        ),
        migrations.RemoveField(
            model_name='cabang',
            name='mu',
        ),
    ]
