# Generated by Django 4.0.2 on 2022-10-31 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        ('keuangan', '0002_jurnal_tbl_transaksi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biayapusat',
            name='jenis_keterangan',
        ),
        migrations.RemoveField(
            model_name='biayapusat',
            name='ket_cabang',
        ),
        migrations.RemoveField(
            model_name='biayapusat',
            name='keterangan',
        ),
        migrations.AddField(
            model_name='biayapusat',
            name='bbm',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='biayapusat',
            name='biaya_bank',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='biayapusat',
            name='cabang',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.cabang'),
        ),
        migrations.AddField(
            model_name='biayapusat',
            name='entertaint',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='biayapusat',
            name='foto_copy',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='biayapusat',
            name='jenis_transaksi_bbm',
            field=models.CharField(blank=True, choices=[('', ''), ('1', 'KAS'), ('2', 'UANG MUKA')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='biayapusat',
            name='jenis_transaksi_biaya_bank',
            field=models.CharField(blank=True, choices=[('', ''), ('1', 'KAS'), ('2', 'UANG MUKA')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='biayapusat',
            name='jenis_transaksi_entertaint',
            field=models.CharField(blank=True, choices=[('', ''), ('1', 'KAS'), ('2', 'UANG MUKA')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='biayapusat',
            name='jenis_transaksi_foto_copy',
            field=models.CharField(blank=True, choices=[('', ''), ('1', 'KAS'), ('2', 'UANG MUKA')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='biayapusat',
            name='jenis_transaksi_kas_kecil',
            field=models.CharField(blank=True, choices=[('', ''), ('1', 'KAS'), ('2', 'UANG MUKA')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='biayapusat',
            name='jenis_transaksi_konsumsi',
            field=models.CharField(blank=True, choices=[('', ''), ('1', 'KAS'), ('2', 'UANG MUKA')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='biayapusat',
            name='jenis_transaksi_lain_lain',
            field=models.CharField(blank=True, choices=[('', ''), ('1', 'KAS'), ('2', 'UANG MUKA')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='biayapusat',
            name='jenis_transaksi_listrik',
            field=models.CharField(blank=True, choices=[('', ''), ('1', 'KAS'), ('2', 'UANG MUKA')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='biayapusat',
            name='jenis_transaksi_majalah',
            field=models.CharField(blank=True, choices=[('', ''), ('1', 'KAS'), ('2', 'UANG MUKA')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='biayapusat',
            name='jenis_transaksi_palkir',
            field=models.CharField(blank=True, choices=[('', ''), ('1', 'KAS'), ('2', 'UANG MUKA')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='biayapusat',
            name='jenis_transaksi_pdam',
            field=models.CharField(blank=True, choices=[('', ''), ('1', 'KAS'), ('2', 'UANG MUKA')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='biayapusat',
            name='jenis_transaksi_pemb_lingkungan',
            field=models.CharField(blank=True, choices=[('', ''), ('1', 'KAS'), ('2', 'UANG MUKA')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='biayapusat',
            name='jenis_transaksi_pengiriman',
            field=models.CharField(blank=True, choices=[('', ''), ('1', 'KAS'), ('2', 'UANG MUKA')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='biayapusat',
            name='jenis_transaksi_perlengkapan',
            field=models.CharField(blank=True, choices=[('', ''), ('1', 'KAS'), ('2', 'UANG MUKA')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='biayapusat',
            name='jenis_transaksi_sumbangan',
            field=models.CharField(blank=True, choices=[('', ''), ('1', 'KAS'), ('2', 'UANG MUKA')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='biayapusat',
            name='jenis_transaksi_telepon',
            field=models.CharField(blank=True, choices=[('', ''), ('1', 'KAS'), ('2', 'UANG MUKA')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='biayapusat',
            name='js_trans',
            field=models.CharField(blank=True, choices=[('0', '--PILIH--'), ('1', 'KAS'), ('2', 'BANK BSI')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='biayapusat',
            name='js_trans_kembali',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='biayapusat',
            name='kas_kecil',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='biayapusat',
            name='ket_bbm',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='biayapusat',
            name='ket_biaya_bank',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='biayapusat',
            name='ket_entertaint',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='biayapusat',
            name='ket_foto_copy',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='biayapusat',
            name='ket_kas_kecil',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='biayapusat',
            name='ket_konsumsi',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='biayapusat',
            name='ket_lain_lain',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='biayapusat',
            name='ket_listrik',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='biayapusat',
            name='ket_majalah',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='biayapusat',
            name='ket_palkir',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='biayapusat',
            name='ket_pdam',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='biayapusat',
            name='ket_pemb_lingkungan',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='biayapusat',
            name='ket_penambahan_saldo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='biayapusat',
            name='ket_penambahan_uk',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='biayapusat',
            name='ket_pengembalian_saldo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='biayapusat',
            name='ket_pengembalian_uk',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='biayapusat',
            name='ket_pengiriman',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='biayapusat',
            name='ket_perlengkapan',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='biayapusat',
            name='ket_sumbangan',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='biayapusat',
            name='ket_telpon',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='biayapusat',
            name='konsumsi',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='biayapusat',
            name='lain_lain',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='biayapusat',
            name='listrik',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='biayapusat',
            name='majalah',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='biayapusat',
            name='palkir',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='biayapusat',
            name='pdam',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='biayapusat',
            name='pemb_lingkungan',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='biayapusat',
            name='penambahan_saldo',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='biayapusat',
            name='penambahan_uk',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='biayapusat',
            name='penerimaan_saldo',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='biayapusat',
            name='pengembalian_saldo',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='biayapusat',
            name='pengembalian_uk',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='biayapusat',
            name='pengiriman',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='biayapusat',
            name='perlengkapan',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='biayapusat',
            name='sumbangan',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='biayapusat',
            name='telpon',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='biayapusat',
            name='saldo_akhir',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='biayapusat',
            name='tanggal',
            field=models.DateField(null=True),
        ),
    ]
