# Generated by Django 4.0.2 on 2022-10-31 20:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_cabang_cu_remove_cabang_mdate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('keuangan', '0003_remove_biayapusat_jenis_keterangan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tbl_Akun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_urut', models.IntegerField(blank=True, editable=False, null=True)),
                ('kode_guna', models.CharField(max_length=15)),
                ('coa', models.CharField(max_length=15)),
                ('deskripsi', models.CharField(max_length=5000)),
                ('saldo_mf', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('saldo_krs', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('saldo_pjb', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('status', models.CharField(choices=[('0', 'Tidak Aktif'), ('1', 'Aktif')], max_length=10)),
                ('jenis', models.CharField(blank=True, choices=[('A', 'AKTIVA'), ('P', 'PASSIVA'), ('L', 'RUGI DAN LABA')], max_length=10, null=True)),
                ('view_unit', models.CharField(max_length=10)),
                ('kode_cabang', models.IntegerField(null=True)),
                ('view_cabang', models.CharField(max_length=10)),
                ('tanggal', models.DateField(blank=True, null=True)),
                ('saldo_akhir_pjb', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('layer', models.CharField(blank=True, max_length=5, null=True)),
                ('jenis_laporan', models.CharField(choices=[('A', 'AKTIVA'), ('P', 'PASSIVA'), ('E', 'EKUITAS'), ('PO', 'PENDAPATAN OPS'), ('BO', 'BEBAN OPS'), ('PNO', 'PENDAPATAN NON OPS'), ('BNO', 'BEBAN NON OPS'), ('K', 'KONTIGEN'), ('KS', 'KONTIGENSI')], max_length=30)),
                ('header_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='keuangan.tbl_akun')),
            ],
            options={
                'db_table': 'tbl_akun',
            },
        ),
        migrations.CreateModel(
            name='BiayaMapper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(blank=True, choices=[('parkir', 'PARKIR'), ('bbm', 'BBM'), ('materai', 'MATERAI'), ('fotocopy', 'FOTO COPY'), ('lingkungan', 'LINGKUNGAN'), ('sumbangan', 'SUMBANGAN'), ('perlengkapan', 'PERLENGKAPAN'), ('konsumsi', 'KONSUMSI'), ('majalah', 'MAJALAH'), ('listrik', 'LISTRIK'), ('lain_lain', 'LAIN_LAIN'), ('telepon', 'TELEPON'), ('pdam', 'PDAM'), ('sewa', 'SEWA'), ('gaji', 'GAJI'), ('transport', 'TRANSPORT'), ('peralkantor', 'PERALKANTOR'), ('adm_bank', 'ADM BANK'), ('pengiriman', 'PENGIRIMAN'), ('penjualan_materai', 'PENJUALAN MATERAI'), ('pembelian_materai', 'Pembelian Materai'), ('entertaint', 'ENTERTAINT')], max_length=50, null=True)),
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('mdate', models.DateTimeField(auto_now=True)),
                ('apcabang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.cabang')),
                ('coa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='keuangan.tbl_akun')),
                ('coa_debet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='keuangan.tbl_akun')),
                ('coa_uk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='keuangan.tbl_akun')),
                ('cu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cu_mep', to=settings.AUTH_USER_MODEL)),
                ('mu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mu_mep', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'biayamapper',
            },
        ),
    ]
