# Generated by Django 4.0.2 on 2022-10-31 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keuangan', '0004_tbl_akun_biayamapper'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_transaksi',
            name='id_product',
            field=models.IntegerField(null=True),
        ),
    ]
