# Generated by Django 4.0.2 on 2022-10-31 20:59

import apps.keuangan.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('keuangan', '0005_tbl_transaksi_id_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jurnal_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diskripsi', models.CharField(blank=True, max_length=200, null=True)),
                ('no_akad', models.IntegerField(blank=True, default=apps.keuangan.models.number, null=True)),
                ('tgl_trans', models.DateField(blank=True, null=True)),
                ('j_status', models.CharField(choices=[('0', 'NON BANK'), ('1', 'BANK'), ('2', 'J.Pendapatan')], default=0, max_length=1)),
                ('object_id', models.IntegerField(blank=True, null=True)),
                ('kode_cabang', models.CharField(blank=True, max_length=5, null=True)),
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('mdate', models.DateTimeField(auto_now=True)),
                ('cu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('mu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'jurnal_history',
            },
        ),
        migrations.CreateModel(
            name='Tbl_Transaksi_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deskripsi', models.CharField(blank=True, max_length=500, null=True)),
                ('no_trans', models.IntegerField(blank=True, null=True)),
                ('jenis', models.CharField(max_length=500)),
                ('debet', models.IntegerField()),
                ('kredit', models.IntegerField()),
                ('id_cabang', models.IntegerField()),
                ('id_cabang_tuju', models.IntegerField(blank=True, null=True)),
                ('id_unit', models.IntegerField()),
                ('id_product', models.IntegerField()),
                ('status_jurnal', models.IntegerField()),
                ('tgl_trans', models.DateField()),
                ('status_posting', models.IntegerField(blank=True, null=True)),
                ('id_coa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='keuangan.tbl_akun')),
                ('jurnal_h', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_items', to='keuangan.jurnal_history')),
                ('user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='c_tbl_transaksi_h', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbl_transaksi_history',
            },
        ),
    ]
