# Generated by Django 4.0.2 on 2022-11-01 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keuangan', '0006_jurnal_history_tbl_transaksi_history'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_akun',
            old_name='saldo_akhir_pjb',
            new_name='saldo_akhir',
        ),
        migrations.RenameField(
            model_name='tbl_akun',
            old_name='saldo_pjb',
            new_name='saldo_awal',
        ),
        migrations.RemoveField(
            model_name='tbl_akun',
            name='saldo_krs',
        ),
        migrations.RemoveField(
            model_name='tbl_akun',
            name='saldo_mf',
        ),
    ]
